# Generated by Django 5.2.7 on 2025-10-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('access_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_in', models.IntegerField(help_text='Tempo de expiração em segundos')),
                ('expires_at', models.DateTimeField(help_text='Data e hora de expiração')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token OAuth',
                'verbose_name_plural': 'Tokens OAuth',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('C2B', 'Customer to Business'), ('B2C', 'Business to Customer')], max_length=10)),
                ('transaction_id', models.CharField(blank=True, help_text='ID da transação retornado pelo M-Pesa', max_length=100, null=True)),
                ('conversation_id', models.CharField(blank=True, help_text='ID da conversa retornado pelo M-Pesa', max_length=100, null=True)),
                ('transaction_reference', models.CharField(db_index=True, help_text='Referência interna da transação', max_length=20)),
                ('third_party_reference', models.CharField(db_index=True, help_text='Referência de terceiros (UUID)', max_length=20)),
                ('customer_msisdn', models.CharField(db_index=True, help_text='Número de telefone do cliente (formato: 258XXXXXXXXX)', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor da transação em Meticais', max_digits=12)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro'), ('pending', 'Pendente')], db_index=True, max_length=20)),
                ('message', models.TextField(blank=True, help_text='Mensagem de sucesso ou erro', null=True)),
                ('raw_response', models.JSONField(blank=True, help_text='Resposta completa da API M-Pesa', null=True)),
                ('from_app', models.CharField(blank=True, help_text='Aplicação de origem (ex: CartaFacil)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='payments_mp_created_f87a30_idx'), models.Index(fields=['customer_msisdn', '-created_at'], name='payments_mp_custome_7eae58_idx'), models.Index(fields=['status', '-created_at'], name='payments_mp_status_6b5caa_idx'), models.Index(fields=['transaction_reference'], name='payments_mp_transac_b401a8_idx')],
            },
        ),
    ]
