# Generated by Django 5.2.6 on 2025-09-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('C2B', 'Customer to Business'), ('B2C', 'Business to Customer')], max_length=3)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_reference', models.CharField(max_length=20)),
                ('third_party_reference', models.CharField(max_length=20)),
                ('customer_msisdn', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
