# Generated by Django 5.2.6 on 2025-09-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=30, unique=True)),
                ('msisdn', models.CharField(blank=True, max_length=9)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('content', models.TextField(blank=True)),
                ('ref_no', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('request_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
