# Generated by Django 5.2.7 on 2025-10-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_emola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='msisdn',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
